/*
 * generated by Xtext 2.13.0
 */
package io.deniffel.dsl.useCase.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class UseCaseWebModule extends AbstractUseCaseWebModule {
}
