/*
 * generated by Xtext 2.13.0
 */
package io.deniffel.dsl.useCase


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class UseCaseStandaloneSetup extends UseCaseStandaloneSetupGenerated {

	def static void doSetup() {
		new UseCaseStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
