/**
 * generated by Xtext 2.13.0
 */
package io.deniffel.dsl.useCase.ui;

import io.deniffel.dsl.useCase.ui.AbstractUseCaseUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class UseCaseUiModule extends AbstractUseCaseUiModule {
  public UseCaseUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
