/*
 * generated by Xtext 2.13.0
 */
package io.deniffel.dsl.useCase.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link UseCaseWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractUseCaseWebModule extends DefaultWebModule {

}
