/*
 * generated by Xtext 2.13.0
 */
package io.deniffel.dsl.useCase.idea.highlighting;

import io.deniffel.dsl.useCase.idea.lang.UseCaseLanguage;
import org.eclipse.xtext.idea.highlighting.AbstractColorSettingsPage;

public class UseCaseBaseColorSettingsPage extends AbstractColorSettingsPage {
	
	public UseCaseBaseColorSettingsPage() {
		UseCaseLanguage.INSTANCE.injectMembers(this);
	}

	@Override
	public String getDisplayName() {
		return UseCaseLanguage.INSTANCE.getDisplayName();
	}
}
