/*
 * generated by Xtext 2.13.0
 */
package io.deniffel.dsl.useCase.idea.highlighting;

import io.deniffel.dsl.useCase.idea.lang.UseCaseLanguage;
import org.eclipse.xtext.idea.highlighting.SemanticHighlightVisitor;

public class UseCaseSemanticHighlightVisitor extends SemanticHighlightVisitor {
	public UseCaseSemanticHighlightVisitor() {
		UseCaseLanguage.INSTANCE.injectMembers(this);
	}
}
