/**
 * generated by Xtext 2.13.0
 */
package io.deniffel.dsl.useCase.ide;

import io.deniffel.dsl.useCase.ide.AbstractUseCaseIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class UseCaseIdeModule extends AbstractUseCaseIdeModule {
}
