/*
 * generated by Xtext 2.13.0
 */
package io.deniffel.dsl.useCase.idea.lang;

import com.intellij.openapi.fileTypes.FileTypeConsumer;
import com.intellij.openapi.fileTypes.FileTypeFactory;
import org.jetbrains.annotations.NotNull;

public class UseCaseFileTypeFactory extends FileTypeFactory {

	@Override
	public void createFileTypes(@NotNull FileTypeConsumer consumer) {
		consumer.consume(UseCaseFileType.INSTANCE, AbstractUseCaseFileType.DEFAULT_EXTENSION);
	}

}
