/*
 * generated by Xtext 2.13.0
 */
package io.deniffel.dsl.useCase.idea.lang;

import com.intellij.psi.tree.IFileElementType;
import io.deniffel.dsl.useCase.idea.lang.psi.impl.UseCaseFileImpl;
import io.deniffel.dsl.useCase.services.UseCaseGrammarAccess;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.idea.lang.IElementTypeProvider;
import org.eclipse.xtext.psi.stubs.XtextFileElementType;
import org.eclipse.xtext.psi.stubs.XtextFileStub;
import org.eclipse.xtext.psi.tree.IGrammarAwareElementType;

public class UseCaseElementTypeProvider implements IElementTypeProvider {

	public static final IFileElementType FILE_TYPE = new XtextFileElementType<XtextFileStub<UseCaseFileImpl>>(UseCaseLanguage.INSTANCE);

	private static final Map<EObject, IGrammarAwareElementType> GRAMMAR_ELEMENT_TYPE = new HashMap<EObject, IGrammarAwareElementType>();

	private static IGrammarAwareElementType associate(IGrammarAwareElementType grammarAwareElementType) {
		GRAMMAR_ELEMENT_TYPE.put(grammarAwareElementType.getGrammarElement(), grammarAwareElementType);
		return grammarAwareElementType;
	}

	private static final UseCaseGrammarAccess GRAMMAR_ACCESS = UseCaseLanguage.INSTANCE.getInstance(UseCaseGrammarAccess.class);

	private static class ModelFactory {
		public static IGrammarAwareElementType createModelElementType() {
			return new IGrammarAwareElementType("Model_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getModelRule());
		}
		public static IGrammarAwareElementType createModel_GroupElementType() {
			return new IGrammarAwareElementType("Model_Group_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getModelAccess().getGroup());
		}
		public static IGrammarAwareElementType createModel_TypesAssignment_0ElementType() {
			return new IGrammarAwareElementType("Model_TypesAssignment_0_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getModelAccess().getTypesAssignment_0());
		}
		public static IGrammarAwareElementType createModel_TypesTypeParserRuleCall_0_0ElementType() {
			return new IGrammarAwareElementType("Model_TypesTypeParserRuleCall_0_0_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getModelAccess().getTypesTypeParserRuleCall_0_0());
		}
		public static IGrammarAwareElementType createModel_UseCasesAssignment_1ElementType() {
			return new IGrammarAwareElementType("Model_UseCasesAssignment_1_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getModelAccess().getUseCasesAssignment_1());
		}
		public static IGrammarAwareElementType createModel_UseCasesUseCaseParserRuleCall_1_0ElementType() {
			return new IGrammarAwareElementType("Model_UseCasesUseCaseParserRuleCall_1_0_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getModelAccess().getUseCasesUseCaseParserRuleCall_1_0());
		}
	}

	public static final IGrammarAwareElementType Model_ELEMENT_TYPE = associate(ModelFactory.createModelElementType());

	public static final IGrammarAwareElementType Model_Group_ELEMENT_TYPE = associate(ModelFactory.createModel_GroupElementType());

	public static final IGrammarAwareElementType Model_TypesAssignment_0_ELEMENT_TYPE = associate(ModelFactory.createModel_TypesAssignment_0ElementType());

	public static final IGrammarAwareElementType Model_TypesTypeParserRuleCall_0_0_ELEMENT_TYPE = associate(ModelFactory.createModel_TypesTypeParserRuleCall_0_0ElementType());

	public static final IGrammarAwareElementType Model_UseCasesAssignment_1_ELEMENT_TYPE = associate(ModelFactory.createModel_UseCasesAssignment_1ElementType());

	public static final IGrammarAwareElementType Model_UseCasesUseCaseParserRuleCall_1_0_ELEMENT_TYPE = associate(ModelFactory.createModel_UseCasesUseCaseParserRuleCall_1_0ElementType());

	private static class UseCaseFactory {
		public static IGrammarAwareElementType createUseCaseElementType() {
			return new IGrammarAwareElementType("UseCase_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getUseCaseRule());
		}
		public static IGrammarAwareElementType createUseCase_GroupElementType() {
			return new IGrammarAwareElementType("UseCase_Group_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getUseCaseAccess().getGroup());
		}
		public static IGrammarAwareElementType createUseCase_UseCaseKeyword_0ElementType() {
			return new IGrammarAwareElementType("UseCase_UseCaseKeyword_0_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getUseCaseAccess().getUseCaseKeyword_0());
		}
		public static IGrammarAwareElementType createUseCase_NameAssignment_1ElementType() {
			return new IGrammarAwareElementType("UseCase_NameAssignment_1_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getUseCaseAccess().getNameAssignment_1());
		}
		public static IGrammarAwareElementType createUseCase_NameSTRINGTerminalRuleCall_1_0ElementType() {
			return new IGrammarAwareElementType("UseCase_NameSTRINGTerminalRuleCall_1_0_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getUseCaseAccess().getNameSTRINGTerminalRuleCall_1_0());
		}
		public static IGrammarAwareElementType createUseCase_DescriptionsAssignment_2ElementType() {
			return new IGrammarAwareElementType("UseCase_DescriptionsAssignment_2_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getUseCaseAccess().getDescriptionsAssignment_2());
		}
		public static IGrammarAwareElementType createUseCase_DescriptionsDescriptionParserRuleCall_2_0ElementType() {
			return new IGrammarAwareElementType("UseCase_DescriptionsDescriptionParserRuleCall_2_0_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getUseCaseAccess().getDescriptionsDescriptionParserRuleCall_2_0());
		}
		public static IGrammarAwareElementType createUseCase_SectionsAssignment_3ElementType() {
			return new IGrammarAwareElementType("UseCase_SectionsAssignment_3_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getUseCaseAccess().getSectionsAssignment_3());
		}
		public static IGrammarAwareElementType createUseCase_SectionsAttributesParserRuleCall_3_0ElementType() {
			return new IGrammarAwareElementType("UseCase_SectionsAttributesParserRuleCall_3_0_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getUseCaseAccess().getSectionsAttributesParserRuleCall_3_0());
		}
		public static IGrammarAwareElementType createUseCase_AllowedUserGroupsAssignment_4ElementType() {
			return new IGrammarAwareElementType("UseCase_AllowedUserGroupsAssignment_4_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getUseCaseAccess().getAllowedUserGroupsAssignment_4());
		}
		public static IGrammarAwareElementType createUseCase_AllowedUserGroupsAllowedUserGroupsParserRuleCall_4_0ElementType() {
			return new IGrammarAwareElementType("UseCase_AllowedUserGroupsAllowedUserGroupsParserRuleCall_4_0_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getUseCaseAccess().getAllowedUserGroupsAllowedUserGroupsParserRuleCall_4_0());
		}
		public static IGrammarAwareElementType createUseCase_EndKeyword_5ElementType() {
			return new IGrammarAwareElementType("UseCase_EndKeyword_5_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getUseCaseAccess().getEndKeyword_5());
		}
		public static IGrammarAwareElementType createUseCase_OfKeyword_6ElementType() {
			return new IGrammarAwareElementType("UseCase_OfKeyword_6_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getUseCaseAccess().getOfKeyword_6());
		}
		public static IGrammarAwareElementType createUseCase_UseCaseKeyword_7ElementType() {
			return new IGrammarAwareElementType("UseCase_UseCaseKeyword_7_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getUseCaseAccess().getUseCaseKeyword_7());
		}
	}

	public static final IGrammarAwareElementType UseCase_ELEMENT_TYPE = associate(UseCaseFactory.createUseCaseElementType());

	public static final IGrammarAwareElementType UseCase_Group_ELEMENT_TYPE = associate(UseCaseFactory.createUseCase_GroupElementType());

	public static final IGrammarAwareElementType UseCase_UseCaseKeyword_0_ELEMENT_TYPE = associate(UseCaseFactory.createUseCase_UseCaseKeyword_0ElementType());

	public static final IGrammarAwareElementType UseCase_NameAssignment_1_ELEMENT_TYPE = associate(UseCaseFactory.createUseCase_NameAssignment_1ElementType());

	public static final IGrammarAwareElementType UseCase_NameSTRINGTerminalRuleCall_1_0_ELEMENT_TYPE = associate(UseCaseFactory.createUseCase_NameSTRINGTerminalRuleCall_1_0ElementType());

	public static final IGrammarAwareElementType UseCase_DescriptionsAssignment_2_ELEMENT_TYPE = associate(UseCaseFactory.createUseCase_DescriptionsAssignment_2ElementType());

	public static final IGrammarAwareElementType UseCase_DescriptionsDescriptionParserRuleCall_2_0_ELEMENT_TYPE = associate(UseCaseFactory.createUseCase_DescriptionsDescriptionParserRuleCall_2_0ElementType());

	public static final IGrammarAwareElementType UseCase_SectionsAssignment_3_ELEMENT_TYPE = associate(UseCaseFactory.createUseCase_SectionsAssignment_3ElementType());

	public static final IGrammarAwareElementType UseCase_SectionsAttributesParserRuleCall_3_0_ELEMENT_TYPE = associate(UseCaseFactory.createUseCase_SectionsAttributesParserRuleCall_3_0ElementType());

	public static final IGrammarAwareElementType UseCase_AllowedUserGroupsAssignment_4_ELEMENT_TYPE = associate(UseCaseFactory.createUseCase_AllowedUserGroupsAssignment_4ElementType());

	public static final IGrammarAwareElementType UseCase_AllowedUserGroupsAllowedUserGroupsParserRuleCall_4_0_ELEMENT_TYPE = associate(UseCaseFactory.createUseCase_AllowedUserGroupsAllowedUserGroupsParserRuleCall_4_0ElementType());

	public static final IGrammarAwareElementType UseCase_EndKeyword_5_ELEMENT_TYPE = associate(UseCaseFactory.createUseCase_EndKeyword_5ElementType());

	public static final IGrammarAwareElementType UseCase_OfKeyword_6_ELEMENT_TYPE = associate(UseCaseFactory.createUseCase_OfKeyword_6ElementType());

	public static final IGrammarAwareElementType UseCase_UseCaseKeyword_7_ELEMENT_TYPE = associate(UseCaseFactory.createUseCase_UseCaseKeyword_7ElementType());

	private static class DescriptionFactory {
		public static IGrammarAwareElementType createDescriptionElementType() {
			return new IGrammarAwareElementType("Description_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getDescriptionRule());
		}
		public static IGrammarAwareElementType createDescription_GroupElementType() {
			return new IGrammarAwareElementType("Description_Group_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getDescriptionAccess().getGroup());
		}
		public static IGrammarAwareElementType createDescription_DescriptionKeyword_0ElementType() {
			return new IGrammarAwareElementType("Description_DescriptionKeyword_0_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getDescriptionAccess().getDescriptionKeyword_0());
		}
		public static IGrammarAwareElementType createDescription_NameAssignment_1ElementType() {
			return new IGrammarAwareElementType("Description_NameAssignment_1_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getDescriptionAccess().getNameAssignment_1());
		}
		public static IGrammarAwareElementType createDescription_NameSTRINGTerminalRuleCall_1_0ElementType() {
			return new IGrammarAwareElementType("Description_NameSTRINGTerminalRuleCall_1_0_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getDescriptionAccess().getNameSTRINGTerminalRuleCall_1_0());
		}
	}

	public static final IGrammarAwareElementType Description_ELEMENT_TYPE = associate(DescriptionFactory.createDescriptionElementType());

	public static final IGrammarAwareElementType Description_Group_ELEMENT_TYPE = associate(DescriptionFactory.createDescription_GroupElementType());

	public static final IGrammarAwareElementType Description_DescriptionKeyword_0_ELEMENT_TYPE = associate(DescriptionFactory.createDescription_DescriptionKeyword_0ElementType());

	public static final IGrammarAwareElementType Description_NameAssignment_1_ELEMENT_TYPE = associate(DescriptionFactory.createDescription_NameAssignment_1ElementType());

	public static final IGrammarAwareElementType Description_NameSTRINGTerminalRuleCall_1_0_ELEMENT_TYPE = associate(DescriptionFactory.createDescription_NameSTRINGTerminalRuleCall_1_0ElementType());

	private static class AttributesFactory {
		public static IGrammarAwareElementType createAttributesElementType() {
			return new IGrammarAwareElementType("Attributes_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getAttributesRule());
		}
		public static IGrammarAwareElementType createAttributes_GroupElementType() {
			return new IGrammarAwareElementType("Attributes_Group_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getAttributesAccess().getGroup());
		}
		public static IGrammarAwareElementType createAttributes_AttributesKeyword_0ElementType() {
			return new IGrammarAwareElementType("Attributes_AttributesKeyword_0_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getAttributesAccess().getAttributesKeyword_0());
		}
		public static IGrammarAwareElementType createAttributes_AttrsAssignment_1ElementType() {
			return new IGrammarAwareElementType("Attributes_AttrsAssignment_1_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getAttributesAccess().getAttrsAssignment_1());
		}
		public static IGrammarAwareElementType createAttributes_AttrsAttributeParserRuleCall_1_0ElementType() {
			return new IGrammarAwareElementType("Attributes_AttrsAttributeParserRuleCall_1_0_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getAttributesAccess().getAttrsAttributeParserRuleCall_1_0());
		}
	}

	public static final IGrammarAwareElementType Attributes_ELEMENT_TYPE = associate(AttributesFactory.createAttributesElementType());

	public static final IGrammarAwareElementType Attributes_Group_ELEMENT_TYPE = associate(AttributesFactory.createAttributes_GroupElementType());

	public static final IGrammarAwareElementType Attributes_AttributesKeyword_0_ELEMENT_TYPE = associate(AttributesFactory.createAttributes_AttributesKeyword_0ElementType());

	public static final IGrammarAwareElementType Attributes_AttrsAssignment_1_ELEMENT_TYPE = associate(AttributesFactory.createAttributes_AttrsAssignment_1ElementType());

	public static final IGrammarAwareElementType Attributes_AttrsAttributeParserRuleCall_1_0_ELEMENT_TYPE = associate(AttributesFactory.createAttributes_AttrsAttributeParserRuleCall_1_0ElementType());

	private static class TypeFactory {
		public static IGrammarAwareElementType createTypeElementType() {
			return new IGrammarAwareElementType("Type_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getTypeRule());
		}
		public static IGrammarAwareElementType createType_GroupElementType() {
			return new IGrammarAwareElementType("Type_Group_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getTypeAccess().getGroup());
		}
		public static IGrammarAwareElementType createType_TypeKeyword_0ElementType() {
			return new IGrammarAwareElementType("Type_TypeKeyword_0_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getTypeAccess().getTypeKeyword_0());
		}
		public static IGrammarAwareElementType createType_NameAssignment_1ElementType() {
			return new IGrammarAwareElementType("Type_NameAssignment_1_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getTypeAccess().getNameAssignment_1());
		}
		public static IGrammarAwareElementType createType_NameIDTerminalRuleCall_1_0ElementType() {
			return new IGrammarAwareElementType("Type_NameIDTerminalRuleCall_1_0_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getTypeAccess().getNameIDTerminalRuleCall_1_0());
		}
		public static IGrammarAwareElementType createType_LeftParenthesisKeyword_2ElementType() {
			return new IGrammarAwareElementType("Type_LeftParenthesisKeyword_2_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getTypeAccess().getLeftParenthesisKeyword_2());
		}
		public static IGrammarAwareElementType createType_DescriptionAssignment_3ElementType() {
			return new IGrammarAwareElementType("Type_DescriptionAssignment_3_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getTypeAccess().getDescriptionAssignment_3());
		}
		public static IGrammarAwareElementType createType_DescriptionSTRINGTerminalRuleCall_3_0ElementType() {
			return new IGrammarAwareElementType("Type_DescriptionSTRINGTerminalRuleCall_3_0_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getTypeAccess().getDescriptionSTRINGTerminalRuleCall_3_0());
		}
		public static IGrammarAwareElementType createType_RightParenthesisKeyword_4ElementType() {
			return new IGrammarAwareElementType("Type_RightParenthesisKeyword_4_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getTypeAccess().getRightParenthesisKeyword_4());
		}
		public static IGrammarAwareElementType createType_Group_5ElementType() {
			return new IGrammarAwareElementType("Type_Group_5_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getTypeAccess().getGroup_5());
		}
		public static IGrammarAwareElementType createType_LeftSquareBracketKeyword_5_0ElementType() {
			return new IGrammarAwareElementType("Type_LeftSquareBracketKeyword_5_0_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getTypeAccess().getLeftSquareBracketKeyword_5_0());
		}
		public static IGrammarAwareElementType createType_ImportInfoAssignment_5_1ElementType() {
			return new IGrammarAwareElementType("Type_ImportInfoAssignment_5_1_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getTypeAccess().getImportInfoAssignment_5_1());
		}
		public static IGrammarAwareElementType createType_ImportInfoQualifiedNameParserRuleCall_5_1_0ElementType() {
			return new IGrammarAwareElementType("Type_ImportInfoQualifiedNameParserRuleCall_5_1_0_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getTypeAccess().getImportInfoQualifiedNameParserRuleCall_5_1_0());
		}
		public static IGrammarAwareElementType createType_RightSquareBracketKeyword_5_2ElementType() {
			return new IGrammarAwareElementType("Type_RightSquareBracketKeyword_5_2_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getTypeAccess().getRightSquareBracketKeyword_5_2());
		}
	}

	public static final IGrammarAwareElementType Type_ELEMENT_TYPE = associate(TypeFactory.createTypeElementType());

	public static final IGrammarAwareElementType Type_Group_ELEMENT_TYPE = associate(TypeFactory.createType_GroupElementType());

	public static final IGrammarAwareElementType Type_TypeKeyword_0_ELEMENT_TYPE = associate(TypeFactory.createType_TypeKeyword_0ElementType());

	public static final IGrammarAwareElementType Type_NameAssignment_1_ELEMENT_TYPE = associate(TypeFactory.createType_NameAssignment_1ElementType());

	public static final IGrammarAwareElementType Type_NameIDTerminalRuleCall_1_0_ELEMENT_TYPE = associate(TypeFactory.createType_NameIDTerminalRuleCall_1_0ElementType());

	public static final IGrammarAwareElementType Type_LeftParenthesisKeyword_2_ELEMENT_TYPE = associate(TypeFactory.createType_LeftParenthesisKeyword_2ElementType());

	public static final IGrammarAwareElementType Type_DescriptionAssignment_3_ELEMENT_TYPE = associate(TypeFactory.createType_DescriptionAssignment_3ElementType());

	public static final IGrammarAwareElementType Type_DescriptionSTRINGTerminalRuleCall_3_0_ELEMENT_TYPE = associate(TypeFactory.createType_DescriptionSTRINGTerminalRuleCall_3_0ElementType());

	public static final IGrammarAwareElementType Type_RightParenthesisKeyword_4_ELEMENT_TYPE = associate(TypeFactory.createType_RightParenthesisKeyword_4ElementType());

	public static final IGrammarAwareElementType Type_Group_5_ELEMENT_TYPE = associate(TypeFactory.createType_Group_5ElementType());

	public static final IGrammarAwareElementType Type_LeftSquareBracketKeyword_5_0_ELEMENT_TYPE = associate(TypeFactory.createType_LeftSquareBracketKeyword_5_0ElementType());

	public static final IGrammarAwareElementType Type_ImportInfoAssignment_5_1_ELEMENT_TYPE = associate(TypeFactory.createType_ImportInfoAssignment_5_1ElementType());

	public static final IGrammarAwareElementType Type_ImportInfoQualifiedNameParserRuleCall_5_1_0_ELEMENT_TYPE = associate(TypeFactory.createType_ImportInfoQualifiedNameParserRuleCall_5_1_0ElementType());

	public static final IGrammarAwareElementType Type_RightSquareBracketKeyword_5_2_ELEMENT_TYPE = associate(TypeFactory.createType_RightSquareBracketKeyword_5_2ElementType());

	private static class AttributeFactory {
		public static IGrammarAwareElementType createAttributeElementType() {
			return new IGrammarAwareElementType("Attribute_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getAttributeRule());
		}
		public static IGrammarAwareElementType createAttribute_GroupElementType() {
			return new IGrammarAwareElementType("Attribute_Group_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getAttributeAccess().getGroup());
		}
		public static IGrammarAwareElementType createAttribute_ManyAssignment_0ElementType() {
			return new IGrammarAwareElementType("Attribute_ManyAssignment_0_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getAttributeAccess().getManyAssignment_0());
		}
		public static IGrammarAwareElementType createAttribute_ManyManyKeyword_0_0ElementType() {
			return new IGrammarAwareElementType("Attribute_ManyManyKeyword_0_0_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getAttributeAccess().getManyManyKeyword_0_0());
		}
		public static IGrammarAwareElementType createAttribute_HyphenMinusKeyword_1ElementType() {
			return new IGrammarAwareElementType("Attribute_HyphenMinusKeyword_1_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getAttributeAccess().getHyphenMinusKeyword_1());
		}
		public static IGrammarAwareElementType createAttribute_ContentAssignment_2ElementType() {
			return new IGrammarAwareElementType("Attribute_ContentAssignment_2_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getAttributeAccess().getContentAssignment_2());
		}
		public static IGrammarAwareElementType createAttribute_ContentSTRINGTerminalRuleCall_2_0ElementType() {
			return new IGrammarAwareElementType("Attribute_ContentSTRINGTerminalRuleCall_2_0_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getAttributeAccess().getContentSTRINGTerminalRuleCall_2_0());
		}
		public static IGrammarAwareElementType createAttribute_Group_3ElementType() {
			return new IGrammarAwareElementType("Attribute_Group_3_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getAttributeAccess().getGroup_3());
		}
		public static IGrammarAwareElementType createAttribute_AsKeyword_3_0ElementType() {
			return new IGrammarAwareElementType("Attribute_AsKeyword_3_0_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getAttributeAccess().getAsKeyword_3_0());
		}
		public static IGrammarAwareElementType createAttribute_TypeAssignment_3_1ElementType() {
			return new IGrammarAwareElementType("Attribute_TypeAssignment_3_1_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getAttributeAccess().getTypeAssignment_3_1());
		}
		public static IGrammarAwareElementType createAttribute_TypeTypeCrossReference_3_1_0ElementType() {
			return new IGrammarAwareElementType("Attribute_TypeTypeCrossReference_3_1_0_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getAttributeAccess().getTypeTypeCrossReference_3_1_0());
		}
		public static IGrammarAwareElementType createAttribute_TypeTypeIDTerminalRuleCall_3_1_0_1ElementType() {
			return new IGrammarAwareElementType("Attribute_TypeTypeIDTerminalRuleCall_3_1_0_1_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getAttributeAccess().getTypeTypeIDTerminalRuleCall_3_1_0_1());
		}
	}

	public static final IGrammarAwareElementType Attribute_ELEMENT_TYPE = associate(AttributeFactory.createAttributeElementType());

	public static final IGrammarAwareElementType Attribute_Group_ELEMENT_TYPE = associate(AttributeFactory.createAttribute_GroupElementType());

	public static final IGrammarAwareElementType Attribute_ManyAssignment_0_ELEMENT_TYPE = associate(AttributeFactory.createAttribute_ManyAssignment_0ElementType());

	public static final IGrammarAwareElementType Attribute_ManyManyKeyword_0_0_ELEMENT_TYPE = associate(AttributeFactory.createAttribute_ManyManyKeyword_0_0ElementType());

	public static final IGrammarAwareElementType Attribute_HyphenMinusKeyword_1_ELEMENT_TYPE = associate(AttributeFactory.createAttribute_HyphenMinusKeyword_1ElementType());

	public static final IGrammarAwareElementType Attribute_ContentAssignment_2_ELEMENT_TYPE = associate(AttributeFactory.createAttribute_ContentAssignment_2ElementType());

	public static final IGrammarAwareElementType Attribute_ContentSTRINGTerminalRuleCall_2_0_ELEMENT_TYPE = associate(AttributeFactory.createAttribute_ContentSTRINGTerminalRuleCall_2_0ElementType());

	public static final IGrammarAwareElementType Attribute_Group_3_ELEMENT_TYPE = associate(AttributeFactory.createAttribute_Group_3ElementType());

	public static final IGrammarAwareElementType Attribute_AsKeyword_3_0_ELEMENT_TYPE = associate(AttributeFactory.createAttribute_AsKeyword_3_0ElementType());

	public static final IGrammarAwareElementType Attribute_TypeAssignment_3_1_ELEMENT_TYPE = associate(AttributeFactory.createAttribute_TypeAssignment_3_1ElementType());

	public static final IGrammarAwareElementType Attribute_TypeTypeCrossReference_3_1_0_ELEMENT_TYPE = associate(AttributeFactory.createAttribute_TypeTypeCrossReference_3_1_0ElementType());

	public static final IGrammarAwareElementType Attribute_TypeTypeIDTerminalRuleCall_3_1_0_1_ELEMENT_TYPE = associate(AttributeFactory.createAttribute_TypeTypeIDTerminalRuleCall_3_1_0_1ElementType());

	private static class AllowedUserGroupsFactory {
		public static IGrammarAwareElementType createAllowedUserGroupsElementType() {
			return new IGrammarAwareElementType("AllowedUserGroups_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getAllowedUserGroupsRule());
		}
		public static IGrammarAwareElementType createAllowedUserGroups_GroupElementType() {
			return new IGrammarAwareElementType("AllowedUserGroups_Group_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getAllowedUserGroupsAccess().getGroup());
		}
		public static IGrammarAwareElementType createAllowedUserGroups_AllowedUsergroupsKeyword_0ElementType() {
			return new IGrammarAwareElementType("AllowedUserGroups_AllowedUsergroupsKeyword_0_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getAllowedUserGroupsAccess().getAllowedUsergroupsKeyword_0());
		}
		public static IGrammarAwareElementType createAllowedUserGroups_GroupsAssignment_1ElementType() {
			return new IGrammarAwareElementType("AllowedUserGroups_GroupsAssignment_1_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getAllowedUserGroupsAccess().getGroupsAssignment_1());
		}
		public static IGrammarAwareElementType createAllowedUserGroups_GroupsAllowedUserGroupParserRuleCall_1_0ElementType() {
			return new IGrammarAwareElementType("AllowedUserGroups_GroupsAllowedUserGroupParserRuleCall_1_0_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getAllowedUserGroupsAccess().getGroupsAllowedUserGroupParserRuleCall_1_0());
		}
	}

	public static final IGrammarAwareElementType AllowedUserGroups_ELEMENT_TYPE = associate(AllowedUserGroupsFactory.createAllowedUserGroupsElementType());

	public static final IGrammarAwareElementType AllowedUserGroups_Group_ELEMENT_TYPE = associate(AllowedUserGroupsFactory.createAllowedUserGroups_GroupElementType());

	public static final IGrammarAwareElementType AllowedUserGroups_AllowedUsergroupsKeyword_0_ELEMENT_TYPE = associate(AllowedUserGroupsFactory.createAllowedUserGroups_AllowedUsergroupsKeyword_0ElementType());

	public static final IGrammarAwareElementType AllowedUserGroups_GroupsAssignment_1_ELEMENT_TYPE = associate(AllowedUserGroupsFactory.createAllowedUserGroups_GroupsAssignment_1ElementType());

	public static final IGrammarAwareElementType AllowedUserGroups_GroupsAllowedUserGroupParserRuleCall_1_0_ELEMENT_TYPE = associate(AllowedUserGroupsFactory.createAllowedUserGroups_GroupsAllowedUserGroupParserRuleCall_1_0ElementType());

	private static class AllowedUserGroupFactory {
		public static IGrammarAwareElementType createAllowedUserGroupElementType() {
			return new IGrammarAwareElementType("AllowedUserGroup_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getAllowedUserGroupRule());
		}
		public static IGrammarAwareElementType createAllowedUserGroup_GroupElementType() {
			return new IGrammarAwareElementType("AllowedUserGroup_Group_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getAllowedUserGroupAccess().getGroup());
		}
		public static IGrammarAwareElementType createAllowedUserGroup_ManyAssignment_0ElementType() {
			return new IGrammarAwareElementType("AllowedUserGroup_ManyAssignment_0_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getAllowedUserGroupAccess().getManyAssignment_0());
		}
		public static IGrammarAwareElementType createAllowedUserGroup_ManyManyKeyword_0_0ElementType() {
			return new IGrammarAwareElementType("AllowedUserGroup_ManyManyKeyword_0_0_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getAllowedUserGroupAccess().getManyManyKeyword_0_0());
		}
		public static IGrammarAwareElementType createAllowedUserGroup_HyphenMinusKeyword_1ElementType() {
			return new IGrammarAwareElementType("AllowedUserGroup_HyphenMinusKeyword_1_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getAllowedUserGroupAccess().getHyphenMinusKeyword_1());
		}
		public static IGrammarAwareElementType createAllowedUserGroup_NameAssignment_2ElementType() {
			return new IGrammarAwareElementType("AllowedUserGroup_NameAssignment_2_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getAllowedUserGroupAccess().getNameAssignment_2());
		}
		public static IGrammarAwareElementType createAllowedUserGroup_NameSTRINGTerminalRuleCall_2_0ElementType() {
			return new IGrammarAwareElementType("AllowedUserGroup_NameSTRINGTerminalRuleCall_2_0_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getAllowedUserGroupAccess().getNameSTRINGTerminalRuleCall_2_0());
		}
		public static IGrammarAwareElementType createAllowedUserGroup_Group_3ElementType() {
			return new IGrammarAwareElementType("AllowedUserGroup_Group_3_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getAllowedUserGroupAccess().getGroup_3());
		}
		public static IGrammarAwareElementType createAllowedUserGroup_AsKeyword_3_0ElementType() {
			return new IGrammarAwareElementType("AllowedUserGroup_AsKeyword_3_0_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getAllowedUserGroupAccess().getAsKeyword_3_0());
		}
		public static IGrammarAwareElementType createAllowedUserGroup_TypeAssignment_3_1ElementType() {
			return new IGrammarAwareElementType("AllowedUserGroup_TypeAssignment_3_1_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getAllowedUserGroupAccess().getTypeAssignment_3_1());
		}
		public static IGrammarAwareElementType createAllowedUserGroup_TypeTypeCrossReference_3_1_0ElementType() {
			return new IGrammarAwareElementType("AllowedUserGroup_TypeTypeCrossReference_3_1_0_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getAllowedUserGroupAccess().getTypeTypeCrossReference_3_1_0());
		}
		public static IGrammarAwareElementType createAllowedUserGroup_TypeTypeIDTerminalRuleCall_3_1_0_1ElementType() {
			return new IGrammarAwareElementType("AllowedUserGroup_TypeTypeIDTerminalRuleCall_3_1_0_1_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getAllowedUserGroupAccess().getTypeTypeIDTerminalRuleCall_3_1_0_1());
		}
	}

	public static final IGrammarAwareElementType AllowedUserGroup_ELEMENT_TYPE = associate(AllowedUserGroupFactory.createAllowedUserGroupElementType());

	public static final IGrammarAwareElementType AllowedUserGroup_Group_ELEMENT_TYPE = associate(AllowedUserGroupFactory.createAllowedUserGroup_GroupElementType());

	public static final IGrammarAwareElementType AllowedUserGroup_ManyAssignment_0_ELEMENT_TYPE = associate(AllowedUserGroupFactory.createAllowedUserGroup_ManyAssignment_0ElementType());

	public static final IGrammarAwareElementType AllowedUserGroup_ManyManyKeyword_0_0_ELEMENT_TYPE = associate(AllowedUserGroupFactory.createAllowedUserGroup_ManyManyKeyword_0_0ElementType());

	public static final IGrammarAwareElementType AllowedUserGroup_HyphenMinusKeyword_1_ELEMENT_TYPE = associate(AllowedUserGroupFactory.createAllowedUserGroup_HyphenMinusKeyword_1ElementType());

	public static final IGrammarAwareElementType AllowedUserGroup_NameAssignment_2_ELEMENT_TYPE = associate(AllowedUserGroupFactory.createAllowedUserGroup_NameAssignment_2ElementType());

	public static final IGrammarAwareElementType AllowedUserGroup_NameSTRINGTerminalRuleCall_2_0_ELEMENT_TYPE = associate(AllowedUserGroupFactory.createAllowedUserGroup_NameSTRINGTerminalRuleCall_2_0ElementType());

	public static final IGrammarAwareElementType AllowedUserGroup_Group_3_ELEMENT_TYPE = associate(AllowedUserGroupFactory.createAllowedUserGroup_Group_3ElementType());

	public static final IGrammarAwareElementType AllowedUserGroup_AsKeyword_3_0_ELEMENT_TYPE = associate(AllowedUserGroupFactory.createAllowedUserGroup_AsKeyword_3_0ElementType());

	public static final IGrammarAwareElementType AllowedUserGroup_TypeAssignment_3_1_ELEMENT_TYPE = associate(AllowedUserGroupFactory.createAllowedUserGroup_TypeAssignment_3_1ElementType());

	public static final IGrammarAwareElementType AllowedUserGroup_TypeTypeCrossReference_3_1_0_ELEMENT_TYPE = associate(AllowedUserGroupFactory.createAllowedUserGroup_TypeTypeCrossReference_3_1_0ElementType());

	public static final IGrammarAwareElementType AllowedUserGroup_TypeTypeIDTerminalRuleCall_3_1_0_1_ELEMENT_TYPE = associate(AllowedUserGroupFactory.createAllowedUserGroup_TypeTypeIDTerminalRuleCall_3_1_0_1ElementType());

	private static class QualifiedNameFactory {
		public static IGrammarAwareElementType createQualifiedNameElementType() {
			return new IGrammarAwareElementType("QualifiedName_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getQualifiedNameRule());
		}
		public static IGrammarAwareElementType createQualifiedName_GroupElementType() {
			return new IGrammarAwareElementType("QualifiedName_Group_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getQualifiedNameAccess().getGroup());
		}
		public static IGrammarAwareElementType createQualifiedName_IDTerminalRuleCall_0ElementType() {
			return new IGrammarAwareElementType("QualifiedName_IDTerminalRuleCall_0_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getQualifiedNameAccess().getIDTerminalRuleCall_0());
		}
		public static IGrammarAwareElementType createQualifiedName_Group_1ElementType() {
			return new IGrammarAwareElementType("QualifiedName_Group_1_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getQualifiedNameAccess().getGroup_1());
		}
		public static IGrammarAwareElementType createQualifiedName_FullStopKeyword_1_0ElementType() {
			return new IGrammarAwareElementType("QualifiedName_FullStopKeyword_1_0_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getQualifiedNameAccess().getFullStopKeyword_1_0());
		}
		public static IGrammarAwareElementType createQualifiedName_IDTerminalRuleCall_1_1ElementType() {
			return new IGrammarAwareElementType("QualifiedName_IDTerminalRuleCall_1_1_ELEMENT_TYPE", UseCaseLanguage.INSTANCE, GRAMMAR_ACCESS.getQualifiedNameAccess().getIDTerminalRuleCall_1_1());
		}
	}

	public static final IGrammarAwareElementType QualifiedName_ELEMENT_TYPE = associate(QualifiedNameFactory.createQualifiedNameElementType());

	public static final IGrammarAwareElementType QualifiedName_Group_ELEMENT_TYPE = associate(QualifiedNameFactory.createQualifiedName_GroupElementType());

	public static final IGrammarAwareElementType QualifiedName_IDTerminalRuleCall_0_ELEMENT_TYPE = associate(QualifiedNameFactory.createQualifiedName_IDTerminalRuleCall_0ElementType());

	public static final IGrammarAwareElementType QualifiedName_Group_1_ELEMENT_TYPE = associate(QualifiedNameFactory.createQualifiedName_Group_1ElementType());

	public static final IGrammarAwareElementType QualifiedName_FullStopKeyword_1_0_ELEMENT_TYPE = associate(QualifiedNameFactory.createQualifiedName_FullStopKeyword_1_0ElementType());

	public static final IGrammarAwareElementType QualifiedName_IDTerminalRuleCall_1_1_ELEMENT_TYPE = associate(QualifiedNameFactory.createQualifiedName_IDTerminalRuleCall_1_1ElementType());

	@Override
	public IFileElementType getFileType() {
		return FILE_TYPE;
	}

	@Override
	public IGrammarAwareElementType findElementType(EObject grammarElement) {
		return GRAMMAR_ELEMENT_TYPE.get(grammarElement);
	}
	
	public IGrammarAwareElementType getModelElementType() {
		return Model_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getModel_GroupElementType() {
		return Model_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getModel_TypesAssignment_0ElementType() {
		return Model_TypesAssignment_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getModel_TypesTypeParserRuleCall_0_0ElementType() {
		return Model_TypesTypeParserRuleCall_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getModel_UseCasesAssignment_1ElementType() {
		return Model_UseCasesAssignment_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getModel_UseCasesUseCaseParserRuleCall_1_0ElementType() {
		return Model_UseCasesUseCaseParserRuleCall_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getUseCaseElementType() {
		return UseCase_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getUseCase_GroupElementType() {
		return UseCase_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getUseCase_UseCaseKeyword_0ElementType() {
		return UseCase_UseCaseKeyword_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getUseCase_NameAssignment_1ElementType() {
		return UseCase_NameAssignment_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getUseCase_NameSTRINGTerminalRuleCall_1_0ElementType() {
		return UseCase_NameSTRINGTerminalRuleCall_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getUseCase_DescriptionsAssignment_2ElementType() {
		return UseCase_DescriptionsAssignment_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getUseCase_DescriptionsDescriptionParserRuleCall_2_0ElementType() {
		return UseCase_DescriptionsDescriptionParserRuleCall_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getUseCase_SectionsAssignment_3ElementType() {
		return UseCase_SectionsAssignment_3_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getUseCase_SectionsAttributesParserRuleCall_3_0ElementType() {
		return UseCase_SectionsAttributesParserRuleCall_3_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getUseCase_AllowedUserGroupsAssignment_4ElementType() {
		return UseCase_AllowedUserGroupsAssignment_4_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getUseCase_AllowedUserGroupsAllowedUserGroupsParserRuleCall_4_0ElementType() {
		return UseCase_AllowedUserGroupsAllowedUserGroupsParserRuleCall_4_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getUseCase_EndKeyword_5ElementType() {
		return UseCase_EndKeyword_5_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getUseCase_OfKeyword_6ElementType() {
		return UseCase_OfKeyword_6_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getUseCase_UseCaseKeyword_7ElementType() {
		return UseCase_UseCaseKeyword_7_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDescriptionElementType() {
		return Description_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDescription_GroupElementType() {
		return Description_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDescription_DescriptionKeyword_0ElementType() {
		return Description_DescriptionKeyword_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDescription_NameAssignment_1ElementType() {
		return Description_NameAssignment_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDescription_NameSTRINGTerminalRuleCall_1_0ElementType() {
		return Description_NameSTRINGTerminalRuleCall_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAttributesElementType() {
		return Attributes_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAttributes_GroupElementType() {
		return Attributes_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAttributes_AttributesKeyword_0ElementType() {
		return Attributes_AttributesKeyword_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAttributes_AttrsAssignment_1ElementType() {
		return Attributes_AttrsAssignment_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAttributes_AttrsAttributeParserRuleCall_1_0ElementType() {
		return Attributes_AttrsAttributeParserRuleCall_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getTypeElementType() {
		return Type_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getType_GroupElementType() {
		return Type_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getType_TypeKeyword_0ElementType() {
		return Type_TypeKeyword_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getType_NameAssignment_1ElementType() {
		return Type_NameAssignment_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getType_NameIDTerminalRuleCall_1_0ElementType() {
		return Type_NameIDTerminalRuleCall_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getType_LeftParenthesisKeyword_2ElementType() {
		return Type_LeftParenthesisKeyword_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getType_DescriptionAssignment_3ElementType() {
		return Type_DescriptionAssignment_3_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getType_DescriptionSTRINGTerminalRuleCall_3_0ElementType() {
		return Type_DescriptionSTRINGTerminalRuleCall_3_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getType_RightParenthesisKeyword_4ElementType() {
		return Type_RightParenthesisKeyword_4_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getType_Group_5ElementType() {
		return Type_Group_5_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getType_LeftSquareBracketKeyword_5_0ElementType() {
		return Type_LeftSquareBracketKeyword_5_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getType_ImportInfoAssignment_5_1ElementType() {
		return Type_ImportInfoAssignment_5_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getType_ImportInfoQualifiedNameParserRuleCall_5_1_0ElementType() {
		return Type_ImportInfoQualifiedNameParserRuleCall_5_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getType_RightSquareBracketKeyword_5_2ElementType() {
		return Type_RightSquareBracketKeyword_5_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAttributeElementType() {
		return Attribute_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAttribute_GroupElementType() {
		return Attribute_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAttribute_ManyAssignment_0ElementType() {
		return Attribute_ManyAssignment_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAttribute_ManyManyKeyword_0_0ElementType() {
		return Attribute_ManyManyKeyword_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAttribute_HyphenMinusKeyword_1ElementType() {
		return Attribute_HyphenMinusKeyword_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAttribute_ContentAssignment_2ElementType() {
		return Attribute_ContentAssignment_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAttribute_ContentSTRINGTerminalRuleCall_2_0ElementType() {
		return Attribute_ContentSTRINGTerminalRuleCall_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAttribute_Group_3ElementType() {
		return Attribute_Group_3_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAttribute_AsKeyword_3_0ElementType() {
		return Attribute_AsKeyword_3_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAttribute_TypeAssignment_3_1ElementType() {
		return Attribute_TypeAssignment_3_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAttribute_TypeTypeCrossReference_3_1_0ElementType() {
		return Attribute_TypeTypeCrossReference_3_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAttribute_TypeTypeIDTerminalRuleCall_3_1_0_1ElementType() {
		return Attribute_TypeTypeIDTerminalRuleCall_3_1_0_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAllowedUserGroupsElementType() {
		return AllowedUserGroups_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAllowedUserGroups_GroupElementType() {
		return AllowedUserGroups_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAllowedUserGroups_AllowedUsergroupsKeyword_0ElementType() {
		return AllowedUserGroups_AllowedUsergroupsKeyword_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAllowedUserGroups_GroupsAssignment_1ElementType() {
		return AllowedUserGroups_GroupsAssignment_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAllowedUserGroups_GroupsAllowedUserGroupParserRuleCall_1_0ElementType() {
		return AllowedUserGroups_GroupsAllowedUserGroupParserRuleCall_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAllowedUserGroupElementType() {
		return AllowedUserGroup_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAllowedUserGroup_GroupElementType() {
		return AllowedUserGroup_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAllowedUserGroup_ManyAssignment_0ElementType() {
		return AllowedUserGroup_ManyAssignment_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAllowedUserGroup_ManyManyKeyword_0_0ElementType() {
		return AllowedUserGroup_ManyManyKeyword_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAllowedUserGroup_HyphenMinusKeyword_1ElementType() {
		return AllowedUserGroup_HyphenMinusKeyword_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAllowedUserGroup_NameAssignment_2ElementType() {
		return AllowedUserGroup_NameAssignment_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAllowedUserGroup_NameSTRINGTerminalRuleCall_2_0ElementType() {
		return AllowedUserGroup_NameSTRINGTerminalRuleCall_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAllowedUserGroup_Group_3ElementType() {
		return AllowedUserGroup_Group_3_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAllowedUserGroup_AsKeyword_3_0ElementType() {
		return AllowedUserGroup_AsKeyword_3_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAllowedUserGroup_TypeAssignment_3_1ElementType() {
		return AllowedUserGroup_TypeAssignment_3_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAllowedUserGroup_TypeTypeCrossReference_3_1_0ElementType() {
		return AllowedUserGroup_TypeTypeCrossReference_3_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAllowedUserGroup_TypeTypeIDTerminalRuleCall_3_1_0_1ElementType() {
		return AllowedUserGroup_TypeTypeIDTerminalRuleCall_3_1_0_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getQualifiedNameElementType() {
		return QualifiedName_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getQualifiedName_GroupElementType() {
		return QualifiedName_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getQualifiedName_IDTerminalRuleCall_0ElementType() {
		return QualifiedName_IDTerminalRuleCall_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getQualifiedName_Group_1ElementType() {
		return QualifiedName_Group_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getQualifiedName_FullStopKeyword_1_0ElementType() {
		return QualifiedName_FullStopKeyword_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getQualifiedName_IDTerminalRuleCall_1_1ElementType() {
		return QualifiedName_IDTerminalRuleCall_1_1_ELEMENT_TYPE;
	}

}
