/**
 * generated by Xtext 2.13.0
 */
package io.deniffel.dsl.useCase.web;

import io.deniffel.dsl.useCase.web.AbstractUseCaseWebModule;

/**
 * Use this class to register additional components to be used within the web application.
 */
@SuppressWarnings("all")
public class UseCaseWebModule extends AbstractUseCaseWebModule {
}
