/**
 * generated by Xtext 2.13.0
 */
package io.deniffel.dsl.useCase.validation;

import io.deniffel.dsl.useCase.validation.AbstractUseCaseValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class UseCaseValidator extends AbstractUseCaseValidator {
}
