/**
 * generated by Xtext 2.13.0
 */
package io.deniffel.dsl.useCase.useCase;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.deniffel.dsl.useCase.useCase.Model#getCompany <em>Company</em>}</li>
 *   <li>{@link io.deniffel.dsl.useCase.useCase.Model#getPackage <em>Package</em>}</li>
 *   <li>{@link io.deniffel.dsl.useCase.useCase.Model#getUseCases <em>Use Cases</em>}</li>
 *   <li>{@link io.deniffel.dsl.useCase.useCase.Model#getTypes <em>Types</em>}</li>
 *   <li>{@link io.deniffel.dsl.useCase.useCase.Model#getExceptions <em>Exceptions</em>}</li>
 * </ul>
 *
 * @see io.deniffel.dsl.useCase.useCase.UseCasePackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Company</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Company</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Company</em>' attribute.
   * @see #setCompany(String)
   * @see io.deniffel.dsl.useCase.useCase.UseCasePackage#getModel_Company()
   * @model
   * @generated
   */
  String getCompany();

  /**
   * Sets the value of the '{@link io.deniffel.dsl.useCase.useCase.Model#getCompany <em>Company</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Company</em>' attribute.
   * @see #getCompany()
   * @generated
   */
  void setCompany(String value);

  /**
   * Returns the value of the '<em><b>Package</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Package</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Package</em>' containment reference.
   * @see #setPackage(io.deniffel.dsl.useCase.useCase.Package)
   * @see io.deniffel.dsl.useCase.useCase.UseCasePackage#getModel_Package()
   * @model containment="true"
   * @generated
   */
  io.deniffel.dsl.useCase.useCase.Package getPackage();

  /**
   * Sets the value of the '{@link io.deniffel.dsl.useCase.useCase.Model#getPackage <em>Package</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Package</em>' containment reference.
   * @see #getPackage()
   * @generated
   */
  void setPackage(io.deniffel.dsl.useCase.useCase.Package value);

  /**
   * Returns the value of the '<em><b>Use Cases</b></em>' containment reference list.
   * The list contents are of type {@link io.deniffel.dsl.useCase.useCase.UseCase}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Use Cases</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Use Cases</em>' containment reference list.
   * @see io.deniffel.dsl.useCase.useCase.UseCasePackage#getModel_UseCases()
   * @model containment="true"
   * @generated
   */
  EList<UseCase> getUseCases();

  /**
   * Returns the value of the '<em><b>Types</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Types</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Types</em>' containment reference.
   * @see #setTypes(UsedTypes)
   * @see io.deniffel.dsl.useCase.useCase.UseCasePackage#getModel_Types()
   * @model containment="true"
   * @generated
   */
  UsedTypes getTypes();

  /**
   * Sets the value of the '{@link io.deniffel.dsl.useCase.useCase.Model#getTypes <em>Types</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Types</em>' containment reference.
   * @see #getTypes()
   * @generated
   */
  void setTypes(UsedTypes value);

  /**
   * Returns the value of the '<em><b>Exceptions</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Exceptions</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exceptions</em>' containment reference.
   * @see #setExceptions(UsedExceptions)
   * @see io.deniffel.dsl.useCase.useCase.UseCasePackage#getModel_Exceptions()
   * @model containment="true"
   * @generated
   */
  UsedExceptions getExceptions();

  /**
   * Sets the value of the '{@link io.deniffel.dsl.useCase.useCase.Model#getExceptions <em>Exceptions</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exceptions</em>' containment reference.
   * @see #getExceptions()
   * @generated
   */
  void setExceptions(UsedExceptions value);

} // Model
