/**
 * generated by Xtext 2.14.0
 */
package io.deniffel.dsl.useCase.useCase;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Step</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.deniffel.dsl.useCase.useCase.Step#getNumber <em>Number</em>}</li>
 *   <li>{@link io.deniffel.dsl.useCase.useCase.Step#getAction <em>Action</em>}</li>
 *   <li>{@link io.deniffel.dsl.useCase.useCase.Step#getError <em>Error</em>}</li>
 *   <li>{@link io.deniffel.dsl.useCase.useCase.Step#getCondition <em>Condition</em>}</li>
 *   <li>{@link io.deniffel.dsl.useCase.useCase.Step#getLoop <em>Loop</em>}</li>
 *   <li>{@link io.deniffel.dsl.useCase.useCase.Step#getException <em>Exception</em>}</li>
 * </ul>
 *
 * @see io.deniffel.dsl.useCase.useCase.UseCasePackage#getStep()
 * @model
 * @generated
 */
public interface Step extends EObject
{
  /**
   * Returns the value of the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Number</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Number</em>' attribute.
   * @see #setNumber(String)
   * @see io.deniffel.dsl.useCase.useCase.UseCasePackage#getStep_Number()
   * @model
   * @generated
   */
  String getNumber();

  /**
   * Sets the value of the '{@link io.deniffel.dsl.useCase.useCase.Step#getNumber <em>Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Number</em>' attribute.
   * @see #getNumber()
   * @generated
   */
  void setNumber(String value);

  /**
   * Returns the value of the '<em><b>Action</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Action</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action</em>' attribute.
   * @see #setAction(String)
   * @see io.deniffel.dsl.useCase.useCase.UseCasePackage#getStep_Action()
   * @model
   * @generated
   */
  String getAction();

  /**
   * Sets the value of the '{@link io.deniffel.dsl.useCase.useCase.Step#getAction <em>Action</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action</em>' attribute.
   * @see #getAction()
   * @generated
   */
  void setAction(String value);

  /**
   * Returns the value of the '<em><b>Error</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Error</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Error</em>' containment reference.
   * @see #setError(RaiseErrorConditional)
   * @see io.deniffel.dsl.useCase.useCase.UseCasePackage#getStep_Error()
   * @model containment="true"
   * @generated
   */
  RaiseErrorConditional getError();

  /**
   * Sets the value of the '{@link io.deniffel.dsl.useCase.useCase.Step#getError <em>Error</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Error</em>' containment reference.
   * @see #getError()
   * @generated
   */
  void setError(RaiseErrorConditional value);

  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Condition</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference.
   * @see #setCondition(IfStatement)
   * @see io.deniffel.dsl.useCase.useCase.UseCasePackage#getStep_Condition()
   * @model containment="true"
   * @generated
   */
  IfStatement getCondition();

  /**
   * Sets the value of the '{@link io.deniffel.dsl.useCase.useCase.Step#getCondition <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' containment reference.
   * @see #getCondition()
   * @generated
   */
  void setCondition(IfStatement value);

  /**
   * Returns the value of the '<em><b>Loop</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Loop</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Loop</em>' containment reference.
   * @see #setLoop(Loop)
   * @see io.deniffel.dsl.useCase.useCase.UseCasePackage#getStep_Loop()
   * @model containment="true"
   * @generated
   */
  Loop getLoop();

  /**
   * Sets the value of the '{@link io.deniffel.dsl.useCase.useCase.Step#getLoop <em>Loop</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Loop</em>' containment reference.
   * @see #getLoop()
   * @generated
   */
  void setLoop(Loop value);

  /**
   * Returns the value of the '<em><b>Exception</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Exception</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exception</em>' containment reference.
   * @see #setException(RaiseErrorNow)
   * @see io.deniffel.dsl.useCase.useCase.UseCasePackage#getStep_Exception()
   * @model containment="true"
   * @generated
   */
  RaiseErrorNow getException();

  /**
   * Sets the value of the '{@link io.deniffel.dsl.useCase.useCase.Step#getException <em>Exception</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exception</em>' containment reference.
   * @see #getException()
   * @generated
   */
  void setException(RaiseErrorNow value);

} // Step
