/*
 * generated by Xtext 2.13.0
 */
package io.deniffel.dsl.useCase.idea.lang.parser;

import com.google.inject.Inject;
import com.intellij.lang.PsiBuilder;
import io.deniffel.dsl.useCase.idea.lang.UseCaseElementTypeProvider;
import io.deniffel.dsl.useCase.idea.parser.antlr.internal.PsiInternalUseCaseParser;
import io.deniffel.dsl.useCase.services.UseCaseGrammarAccess;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;
import org.antlr.runtime.TokenStream;
import org.eclipse.xtext.idea.parser.AbstractPsiAntlrParser;
import org.eclipse.xtext.idea.parser.AbstractXtextPsiParser;

public class UseCasePsiParser extends AbstractXtextPsiParser {

	private static final Set<String> INITIAL_HIDDEN_TOKENS = new HashSet<String>(Arrays.asList("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT"));

	@Inject 
	private UseCaseGrammarAccess grammarAccess;

	@Inject 
	private UseCaseElementTypeProvider elementTypeProvider;

	@Override
	protected AbstractPsiAntlrParser createParser(PsiBuilder builder, TokenStream tokenStream) {
		return new PsiInternalUseCaseParser(builder, tokenStream, elementTypeProvider, grammarAccess);
	}

	@Override
	protected Set<String> getInitialHiddenTokens() {
		return INITIAL_HIDDEN_TOKENS;
	}
}
