/**
 * generated by Xtext 2.13.0
 */
package io.deniffel.dsl.useCase.idea.completion;

import io.deniffel.dsl.useCase.idea.completion.AbstractUseCaseCompletionContributor;

@SuppressWarnings("all")
public class UseCaseCompletionContributor extends AbstractUseCaseCompletionContributor {
  public UseCaseCompletionContributor() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe constructor UseCaseCompletionContributor(AbstractXtextLanguage) refers to the missing type AbstractXtextLanguage");
  }
  
  public UseCaseCompletionContributor(final /* AbstractXtextLanguage */Object lang) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method super(AbstractXtextLanguage) is undefined");
  }
}
