/**
 * generated by Xtext 2.13.0
 */
package io.deniffel.dsl.useCase.idea;

import com.google.inject.Injector;
import org.eclipse.xtext.ISetup;

@SuppressWarnings("all")
public class UseCaseIdeaSetup implements ISetup {
  @Override
  public Injector createInjectorAndDoEMFRegistration() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field EcoreGlobalRegistries is undefined"
      + "\nensureInitialized cannot be resolved");
  }
}
