/**
 * generated by Xtext 2.13.0
 */
package io.deniffel.dsl.useCase.idea;

@SuppressWarnings("all")
public class UseCaseIdeaSetup /* implements ISetup  */{
  @Override
  public Object createInjectorAndDoEMFRegistration() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field EcoreGlobalRegistries is undefined"
      + "\nThe method createInjector() from the type UseCaseStandaloneSetupIdea refers to the missing type Object"
      + "\nensureInitialized cannot be resolved");
  }
}
