/**
 * generated by Xtext 2.13.0
 */
package io.deniffel.dsl.useCase.idea;

import com.google.inject.Injector;
import io.deniffel.dsl.useCase.UseCaseStandaloneSetupGenerated;

@SuppressWarnings("all")
public class UseCaseStandaloneSetupIdea extends UseCaseStandaloneSetupGenerated {
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nType mismatch: cannot convert from UseCaseIdeaModule to Module");
  }
}
