/*
 * generated by Xtext 2.13.0
 */
package io.deniffel.dsl.useCase.idea.lang.psi.impl;

import com.intellij.openapi.fileTypes.FileType;
import com.intellij.psi.FileViewProvider;
import io.deniffel.dsl.useCase.idea.lang.UseCaseFileType;
import io.deniffel.dsl.useCase.idea.lang.UseCaseLanguage;
import org.eclipse.xtext.psi.impl.BaseXtextFile;

public final class UseCaseFileImpl extends BaseXtextFile {

	public UseCaseFileImpl(FileViewProvider viewProvider) {
		super(viewProvider, UseCaseLanguage.INSTANCE);
	}

	@Override
	public FileType getFileType() {
		return UseCaseFileType.INSTANCE;
	}
}
