/*
 * generated by Xtext 2.14.0
 */
package io.deniffel.dsl.useCase.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class UseCaseAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("io/deniffel/dsl/useCase/parser/antlr/internal/InternalUseCase.tokens");
	}
}
