/*
 * generated by Xtext 2.13.0
 */
package io.deniffel.dsl.useCase.idea

import org.eclipse.xtext.ISetup
import org.eclipse.xtext.idea.extensions.EcoreGlobalRegistries

class UseCaseIdeaSetup implements ISetup {

	override createInjectorAndDoEMFRegistration() {
		EcoreGlobalRegistries.ensureInitialized
		new UseCaseStandaloneSetupIdea().createInjector
	}

}
