/*
 * generated by Xtext 2.13.0
 */
package io.deniffel.dsl.useCase.idea.completion;

import org.eclipse.xtext.common.idea.completion.TerminalsCompletionContributor;
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public class AbstractUseCaseCompletionContributor extends TerminalsCompletionContributor {
	public AbstractUseCaseCompletionContributor(AbstractXtextLanguage lang) {
		super(lang);
	}
}
