/*
 * generated by Xtext 2.13.0
 */
package io.deniffel.dsl.useCase.idea.completion

import io.deniffel.dsl.useCase.idea.lang.UseCaseLanguage
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage

class UseCaseCompletionContributor extends AbstractUseCaseCompletionContributor {
	new() {
		this(UseCaseLanguage.INSTANCE)
	}
	
	new(AbstractXtextLanguage lang) {
		super(lang)
		//custom rules here
	}
}
